---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#


- name: set general internal vars
  set_fact:
    jdk_version: "1.{{ java_version }}.0_{{ java_subversion }}"


#
# platform-specific variables
#

- name: set java architecture
  set_fact:
    jdk_arch: "{{ 'i586'  if ansible_architecture == 'i386' else 'x64' }}"

- name: set java OS for Linux
  set_fact:
    jdk_os: linux
  when: ansible_system == 'Linux'

- name: set java OS for Mac OS X
  set_fact:
    jdk_os: macosx
  when: ansible_os_family == 'Darwin'


#
# version-specific variables
#

- name: set internal vars for 1.8.0_131
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b11"
    jdk_tarball_hash: d54c1d3a095b4ff2b6607d096fa80163
  when: java_version == 8 and java_subversion == 131

- name: set internal vars for 1.8.0_121
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b13"
    jdk_tarball_hash: e9e7ea248e2c4826b92b3f075a80e441
  when: java_version == 8 and java_subversion == 121

- name: set internal vars for 1.8.0_112
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b15"
    jdk_tarball_hash:
  when: java_version == 8 and java_subversion == 112

- name: set internal vars for 1.8.0_111
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b14"
    jdk_tarball_hash:
  when: java_version == 8 and java_subversion == 111



- name: set internal vars for generic Java version
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b{{ java_build }}"
  when: jdk_version_detail is not defined and java_build is defined


- name: compose filename, if necessary
  set_fact:
    jdk_tarball_file: "jdk-{{ java_version }}u{{ java_subversion }}-{{ jdk_os }}-{{ jdk_arch }}"
  when: jdk_tarball_file is not defined

- name: compose url for downloading file, if necessary
  set_fact:
    jdk_tarball_url:  "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail }}/{{ jdk_tarball_file }}"
  when: jdk_version_detail is defined and jdk_tarball_hash is not defined


- name: compose url for downloading file, if necessary
  set_fact:
    jdk_tarball_url: "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail }}/{{ jdk_tarball_hash }}/{{ jdk_tarball_file }}"
  when: jdk_version_detail is defined and jdk_tarball_hash is defined


#
# JCE variables
#

- name: set JCE variables for java 8
  set_fact:
    jce_zip_file:   "jce_policy-{{ java_version }}.zip"
    jce_zip_folder: "UnlimitedJCEPolicyJDK{{ java_version }}"
  when: java_version == 8

- name: set JCE download file
  set_fact:
    jce_zip_url: "http://download.oracle.com/otn-pub/java/jce/{{ java_version }}/{{ jce_zip_file }}"


#
# directories
#

- name: set java installation directory on Debian platforms
  set_fact:
    java_install_dir: /usr/lib/jvm
    java_default_link_name: default-java
    java_home: /usr/lib/jvm/default-java
  when: ansible_os_family == "Debian"

- name: set java installation directory on Mac OS X
  set_fact:
    # The Java installation directory on Mac OS X is determined by the package itself.
    java_install_dir: /no_such_directory
    java_default_link_name: default
  when: ansible_os_family == "Darwin"

- name: set java installation directory on non-Debian platforms
  set_fact:
    java_install_dir: /usr/java
    java_default_link_name: default
    java_home: /usr/java/default
  when: ansible_os_family != "Debian" and ansible_os_family != "Darwin"
